version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      python-nonmajor:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      docker-nonmajor:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    groups:
      actions-nonmajor:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    labels:
      - "dependencies"
      - "ci"
