"""Create local-only Prometheus configuration; AWS remote-write is opt-in.

No cloud resources are provisioned; no credentials are generated or printed.
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import sys
from pathlib import Path
from typing import Optional

REGION_RE = re.compile(r"^(?:[a-z]{2}|us-gov|cn)-[a-z0-9-]+-[1-9][0-9]*$")
WORKSPACE_RE = re.compile(r"^ws-[a-z0-9-]{8,64}$")
DEFAULT_RUNTIME = Path(__file__).resolve().parent / "runtime"


def prometheus_config(region: Optional[str] = None, workspace: Optional[str] = None) -> str:
    if (region is None) != (workspace is None):
        raise ValueError("region and workspace must be supplied together")
    if region is not None and (not REGION_RE.fullmatch(region) or not WORKSPACE_RE.fullmatch(workspace)):
        raise ValueError("invalid AWS region or AMP workspace identifier")
    content = """# Generated by GPT-Doug; locally scoped telemetry only.
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  external_labels:
    service: gpt-doug
scrape_configs:
  - job_name: gpt-doug-api
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/metrics_token
    static_configs:
      - targets: ['gpt-doug-api:9090']
"""
    if region is not None:
        content += f"""remote_write:
  - url: https://aps-workspaces.{region}.amazonaws.com/workspaces/{workspace}/api/v1/remote_write
    sigv4:
      region: {region}
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'gpt_doug_.*'
        action: keep
    queue_config:
      max_shards: 2
      capacity: 500
      max_samples_per_send: 100
"""
    return content


def configure(runtime: Path, *, region: Optional[str] = None, workspace: Optional[str] = None,
              billing_acknowledged: bool = False) -> dict:
    if region is not None and not billing_acknowledged:
        raise ValueError("AWS ingestion may incur charges; --acknowledge-aws-charges is required")
    text = prometheus_config(region, workspace)
    if runtime.is_symlink():
        raise ValueError("runtime directory must not be a symlink")
    runtime.mkdir(parents=True, exist_ok=True, mode=0o700)
    if os.name == "posix":
        runtime.chmod(0o700)
    token_file = runtime / "metrics_token"
    if not token_file.exists():
        # Container users need read permission on this file, but host parent
        # directory remains private (0700), and the file is bind-mounted only.
        fd = os.open(token_file, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
        with os.fdopen(fd, "w", encoding="ascii") as handle:
            handle.write(secrets.token_urlsafe(48) + "\n")
    if token_file.is_symlink() or not token_file.is_file():
        raise ValueError("runtime metrics token must be an ordinary file")
    if not token_file.read_text(encoding="ascii").strip():
        raise ValueError("runtime metrics token is empty")
    # Prometheus image runs unprivileged: individual bind-mounted token file
    # must be readable, while the host runtime directory stays owner-only.
    if os.name == "posix":
        token_file.chmod(0o644)
    config_file = runtime / "prometheus.yml"
    if config_file.is_symlink():
        raise ValueError("runtime config may not be a symlink")
    config_file.write_text(text, encoding="utf-8")
    config_file.chmod(0o644)
    return {
        "mode": "aws_amp_opt_in" if region else "local_only",
        "aws_remote_write_enabled": bool(region),
        "prometheus_config": str(config_file),
        "metrics_token_file": str(token_file),
        "note": "Nothing deployed; run docker compose up -d after inspecting the generated config.",
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", type=Path, default=DEFAULT_RUNTIME)
    parser.add_argument("--amp-region", default=None)
    parser.add_argument("--amp-workspace-id", default=None)
    parser.add_argument("--acknowledge-aws-charges", action="store_true")
    args = parser.parse_args(argv)
    try:
        result = configure(args.runtime, region=args.amp_region,
                           workspace=args.amp_workspace_id,
                           billing_acknowledged=args.acknowledge_aws_charges)
    except (OSError, ValueError) as exc:
        print(f"GPT-DOUG MONITORING: {exc}", file=sys.stderr)
        return 2
    print("GPT-DOUG MONITORING:", result["mode"])
    print("Config:", result["prometheus_config"])
    print("No AWS credentials stored or printed. No cloud resources created.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
