"""Bounded execution for XUNIA security plans.

Only commands generated by :mod:`xunia_security` may be executed. The engagement is
re-authorized immediately before launch. Shell interpreters and privilege escalators are
never accepted, subprocesses are launched with shell=False, and evidence output is bounded.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha256
import shutil
import subprocess
from typing import Callable, Optional, Sequence

from xunia_security import Engagement, PlannedStep, XuniaSecurityPlatform


BLOCKED_BINARIES = {"sh", "bash", "zsh", "fish", "cmd", "cmd.exe", "powershell", "pwsh", "sudo", "su", "doas"}
ALLOWED_BINARIES = {
    "nmap",
    "nuclei",
    "zap-baseline.py",
    "trivy",
    "syft",
    "grype",
    "gitleaks",
    "semgrep",
    "osv-scanner",
    "checkov",
    "prowler",
}


@dataclass(frozen=True)
class ExecutionPolicy:
    timeout_seconds: int = 180
    max_output_bytes: int = 256_000

    def validate(self) -> None:
        if self.timeout_seconds < 1 or self.timeout_seconds > 900:
            raise ValueError("EXECUTION_TIMEOUT_OUT_OF_RANGE")
        if self.max_output_bytes < 1 or self.max_output_bytes > 5_000_000:
            raise ValueError("EXECUTION_OUTPUT_LIMIT_OUT_OF_RANGE")


@dataclass(frozen=True)
class ExecutionEvidence:
    engagement_id: str
    planned_evidence_id: str
    tool_id: str
    target_type: str
    target: str
    argv: tuple[str, ...]
    started_at: str
    finished_at: str
    returncode: int
    stdout_sha256: str
    stderr_sha256: str
    stdout_preview: str
    stderr_preview: str
    output_truncated: bool
    status: str


def _as_bytes(value: object) -> bytes:
    if value is None:
        return b""
    if isinstance(value, bytes):
        return value
    return str(value).encode("utf-8", errors="replace")


def _preview(data: bytes, limit: int) -> tuple[str, bool]:
    truncated = len(data) > limit
    visible = data[:limit]
    return visible.decode("utf-8", errors="replace"), truncated


class AuthorizedToolExecutor:
    """Execute a previously planned XUNIA step under bounded defensive controls."""

    def __init__(
        self,
        platform: Optional[XuniaSecurityPlatform] = None,
        policy: ExecutionPolicy = ExecutionPolicy(),
        binary_resolver: Callable[[str], Optional[str]] = shutil.which,
        runner: Callable[..., subprocess.CompletedProcess] = subprocess.run,
        clock: Callable[[], datetime] = lambda: datetime.now(timezone.utc),
    ) -> None:
        policy.validate()
        self.platform = platform or XuniaSecurityPlatform()
        self.policy = policy
        self.binary_resolver = binary_resolver
        self.runner = runner
        self.clock = clock

    def execute(self, engagement: Engagement, step: PlannedStep) -> ExecutionEvidence:
        authorization_time = self.clock()
        self.platform.authorize_step(engagement, step, authorization_time)

        if not step.argv:
            raise PermissionError("EMPTY_EXECUTION_COMMAND")
        binary = step.argv[0]
        if binary.lower() in BLOCKED_BINARIES:
            raise PermissionError("SHELL_OR_PRIVILEGE_BINARY_DENIED")
        if binary not in ALLOWED_BINARIES:
            raise PermissionError("UNREGISTERED_SECURITY_BINARY")
        resolved = self.binary_resolver(binary)
        if not resolved:
            raise FileNotFoundError(f"SECURITY_BINARY_NOT_INSTALLED:{binary}")

        started = self.clock()
        try:
            completed = self.runner(
                list(step.argv),
                shell=False,
                capture_output=True,
                timeout=self.policy.timeout_seconds,
                check=False,
            )
        except subprocess.TimeoutExpired as exc:
            stdout = _as_bytes(exc.stdout)
            stderr = _as_bytes(exc.stderr)
            finished = self.clock()
            stdout_preview, out_truncated = _preview(stdout, self.policy.max_output_bytes // 2)
            stderr_preview, err_truncated = _preview(stderr, self.policy.max_output_bytes // 2)
            return ExecutionEvidence(
                engagement_id=engagement.engagement_id,
                planned_evidence_id=step.evidence_id,
                tool_id=step.tool.id,
                target_type=step.target.type,
                target=step.target.normalized(),
                argv=step.argv,
                started_at=started.isoformat(),
                finished_at=finished.isoformat(),
                returncode=124,
                stdout_sha256=sha256(stdout).hexdigest(),
                stderr_sha256=sha256(stderr).hexdigest(),
                stdout_preview=stdout_preview,
                stderr_preview=stderr_preview,
                output_truncated=out_truncated or err_truncated,
                status="TIMEOUT",
            )

        stdout = _as_bytes(completed.stdout)
        stderr = _as_bytes(completed.stderr)
        finished = self.clock()
        half_limit = max(1, self.policy.max_output_bytes // 2)
        stdout_preview, out_truncated = _preview(stdout, half_limit)
        stderr_preview, err_truncated = _preview(stderr, half_limit)
        return ExecutionEvidence(
            engagement_id=engagement.engagement_id,
            planned_evidence_id=step.evidence_id,
            tool_id=step.tool.id,
            target_type=step.target.type,
            target=step.target.normalized(),
            argv=step.argv,
            started_at=started.isoformat(),
            finished_at=finished.isoformat(),
            returncode=int(completed.returncode),
            stdout_sha256=sha256(stdout).hexdigest(),
            stderr_sha256=sha256(stderr).hexdigest(),
            stdout_preview=stdout_preview,
            stderr_preview=stderr_preview,
            output_truncated=out_truncated or err_truncated,
            status="COMPLETED" if completed.returncode == 0 else "FAILED",
        )
