apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shaggoth-api
  namespace: shaggoth-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shaggoth-api
