apiVersion: v1
kind: Secret
metadata:
  name: shaggoth-secrets
  namespace: shaggoth-system
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  SHAGGOTH_CONNECT_BEARER_TOKEN: ""
  SHAGGOTH_AUTHORIZED_ENDPOINTS: ""
  SHAGGOTH_MODEL: ""
  SHAGGOTH_BASE_URL: "https://api.openai.com/v1"
