const $=id=>document.getElementById(id),c=$('astro'),x=c.getContext('2d');
const defs=[['solar','SOLAR / HELIOSPHERE','#ffd76e'],['magneto','MAGNETOSPHERE / AURORA','#68ffb1'],['lunar','LUNAR GEOMETRY','#e8edf3'],['planets','PLANETARY EPHEMERIS','#ffb36b'],['neo','NEO / COMET CONTEXT','#ff8ebd'],['deep','DEEP SPACE / STELLAR FIELD','#8db8ff'],['radio','RADIO / EM SKY','#aa83ff']];
const map=Object.fromEntries(defs.map(d=>[d[0],{name:d[1],color:d[2]}]));
const s={active:new Set(defs.map(d=>d[0])),scale:'earth',offset:0,playing:false,labels:true,trails:true,uncertainty:true,pulse:0,panX:0,panY:0,selected:null,objects:[],timer:null};
function fit(){const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);x.setTransform(d,0,0,d,0,0);return r}
function rgba(h,a){const q=h.slice(1);return 'rgba('+parseInt(q.slice(0,2),16)+','+parseInt(q.slice(2,4),16)+','+parseInt(q.slice(4,6),16)+','+a+')'}
function dt(){return new Date(Date.now()+s.offset*3600000)}
function moonPhase(){const k=Date.UTC(2000,0,6,18,14),p=((dt()-k)/86400000%29.53058867+29.53058867)%29.53058867/29.53058867;return p<.03||p>.97?'NEW':p<.22?'WAXING CRESCENT':p<.28?'FIRST QUARTER':p<.47?'WAXING GIBBOUS':p<.53?'FULL':p<.72?'WANING GIBBOUS':p<.78?'LAST QUARTER':'WANING CRESCENT'}
function frame(){return{earth:'EARTH-CENTRIC',lunar:'EARTH / MOON',solar:'HELIOCENTRIC',deep:'DEEP-SPACE CONTEXT'}[s.scale]}
function log(m){const d=document.createElement('div');d.className='event';d.textContent=new Date().toLocaleTimeString()+'  '+m;$('events').prepend(d);while($('events').children.length>12)$('events').lastChild.remove()}
function layers(){const r=$('layers');r.innerHTML='';defs.forEach(d=>{const e=document.createElement('div');e.className='layer'+(s.active.has(d[0])?'':' off');e.innerHTML='<i class="dot" style="background:'+d[2]+';color:'+d[2]+'"></i><div><b>'+d[1]+'</b><br><span>PUBLIC CONTEXT / SYNTHETIC</span></div><em>'+(s.active.has(d[0])?'ON':'OFF')+'</em>';e.onclick=()=>{s.active.has(d[0])?s.active.delete(d[0]):s.active.add(d[0]);layers();build();log(d[1]+' '+(s.active.has(d[0])?'enabled':'disabled'))};r.appendChild(e)})}
function o(id,l,X,Y,R,ctx){return{id,layer:l,x:X,y:Y,r:R,ctx,confidence:90+Math.floor(Math.random()*9)}}
function build(){const r=c.getBoundingClientRect(),w=Math.max(500,r.width),h=Math.max(400,r.height),cx=w/2,cy=h/2,t=dt().getTime()/3600000;s.objects=[];
if(s.active.has('solar'))s.objects.push(o('SOL','solar',cx,cy,14,'HELIOPHYSICS / SIM'));
if(s.active.has('lunar')){const a=t*.009,rr=Math.min(w,h)*.3;s.objects.push(o('LUNA','lunar',cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.55,7,'EPHEMERIS-STYLE / SIM'))}
if(s.active.has('planets'))[['MERCURY',.12],['VENUS',.18],['EARTH',.25],['MARS',.32],['JUPITER',.41],['SATURN',.49]].forEach((p,i)=>{const rr=Math.min(w,h)*p[1],a=t*(.006/(i+1))+i*.8;s.objects.push(o(p[0],'planets',cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.58,3+i*.4,'PLANETARY SIM'))});
if(s.active.has('neo'))for(let i=0;i<7;i++){const a=i*.9+t*.0014,rr=Math.min(w,h)*(.18+i*.035);s.objects.push(o('NEO-'+(i+1),'neo',cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.72,3,'SYNTHETIC CATALOG'))}
if(s.active.has('deep'))[['SIRIUS',.18,.22],['VEGA',.76,.18],['BETELGEUSE',.78,.67],['ANDROMEDA',.22,.73],['PLEIADES',.62,.38]].forEach(p=>s.objects.push(o(p[0],'deep',w*p[1],h*p[2],3,'STELLAR CONTEXT / SIM')));
if(s.active.has('radio'))for(let i=0;i<6;i++)s.objects.push(o('EM-'+(i+1),'radio',w*(.15+i*.14),h*(.2+(i%3)*.22),3,'RADIO/EM SKY / SIM'));
if(s.active.has('magneto'))s.objects.push(o('MAGNETO','magneto',cx+10,cy,9,'SPACE WEATHER / SIM'));$('objectCount').textContent=s.objects.length+' OBJECTS';ui()}
function orbit(cx,cy,rx,ry,col,a=.14){x.strokeStyle=rgba(col,a);x.beginPath();x.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);x.stroke()}
function draw(){const r=fit(),w=r.width,h=r.height,cx=w/2+s.panX,cy=h/2+s.panY,min=Math.min(w,h);x.clearRect(0,0,w,h);x.fillStyle='#02050a';x.fillRect(0,0,w,h);
for(let i=0;i<80;i++){const X=(Math.sin(i*91.7)*.5+.5)*w,Y=(Math.sin(i*37.1+1.8)*.5+.5)*h;x.fillStyle='rgba(190,220,255,'+(.08+(i%7)/12)+')';x.fillRect(X,Y,i%13===0?1.5:.7,i%13===0?1.5:.7)}
if(s.scale==='solar'&&s.active.has('planets'))for(let i=0;i<6;i++){const rr=min*(.12+i*.07);orbit(cx,cy,rr,rr*.58,'#ffb36b')}
if((s.scale==='earth'||s.scale==='lunar')&&s.active.has('magneto')){x.strokeStyle='rgba(104,255,177,.24)';x.beginPath();x.ellipse(cx+8,cy,min*.17,min*.29,0,0,Math.PI*2);x.stroke()}
if(s.active.has('radio')){x.strokeStyle='rgba(170,131,255,.08)';for(let i=0;i<5;i++){x.beginPath();x.moveTo(0,h*(.15+i*.17));x.bezierCurveTo(w*.3,h*.35,w*.65,h*.05,w,h*(.2+i*.14));x.stroke()}}
for(const q of s.objects){const X=q.x+s.panX,Y=q.y+s.panY,sel=s.selected?.id===q.id,R=q.r+(sel?3:0);if(s.uncertainty){x.strokeStyle=rgba(map[q.layer].color,.12);x.beginPath();x.arc(X,Y,R*3.1,0,Math.PI*2);x.stroke()}x.fillStyle=map[q.layer].color;x.beginPath();x.arc(X,Y,R,0,Math.PI*2);x.fill();if(s.trails&&['planets','lunar','neo'].includes(q.layer))orbit(cx,cy,Math.hypot(X-cx,Y-cy),Math.hypot(X-cx,Y-cy)*.62,map[q.layer].color,.08);if(s.labels){x.fillStyle='#afbfce';x.font='7px ui-monospace';x.fillText(q.id,X+R+4,Y-3)}if(sel){x.strokeStyle='#fff';x.setLineDash([3,3]);x.beginPath();x.arc(X,Y,R+6,0,Math.PI*2);x.stroke();x.setLineDash([])}}
if(s.pulse>.01){x.strokeStyle='rgba(255,215,110,'+(s.pulse*.5)+')';for(let i=0;i<4;i++){x.beginPath();x.arc(cx,cy,min*(.08+i*.08)+s.pulse*15,0,Math.PI*2);x.stroke()}s.pulse*=.97}requestAnimationFrame(draw)}
function ui(){$('clock').textContent=new Date().toLocaleTimeString();$('frame').textContent=frame();$('simTime').textContent=s.offset===0?'NOW':(s.offset>0?'+':'')+s.offset+'H';$('moonPhase').textContent='MOON '+moonPhase();$('phaseState').textContent=moonPhase();$('solarState').textContent=s.pulse>.05?'PULSE / SIM':'QUIET / SIM';$('geomagState').textContent=s.pulse>.05?'ELEVATED / SIM':'NOMINAL / SIM';document.querySelectorAll('[data-scale]').forEach(b=>b.classList.toggle('active',b.dataset.scale===s.scale))}
function pick(X,Y){const r=c.getBoundingClientRect(),px=X-r.left,py=Y-r.top;let b=null,d=20;for(const q of s.objects){const z=Math.hypot(px-(q.x+s.panX),py-(q.y+s.panY));if(z<d){d=z;b=q}}if(b){s.selected=b;$('selId').textContent=b.id;$('selLayer').textContent=map[b.layer].name;$('selContext').textContent=b.ctx;$('selConfidence').textContent=b.confidence+'%';$('tags').innerHTML='<span class="tag">'+b.layer.toUpperCase()+'</span><span class="tag">SYNTHETIC</span>';log('Selected '+b.id)}}
let drag=false,lx=0,ly=0,m=false;c.onpointerdown=e=>{drag=true;m=false;lx=e.clientX;ly=e.clientY;c.setPointerCapture?.(e.pointerId)};c.onpointermove=e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>2)m=true;s.panX+=dx;s.panY+=dy;lx=e.clientX;ly=e.clientY};c.onpointerup=e=>{if(!m)pick(e.clientX,e.clientY);drag=false};
document.querySelectorAll('[data-scale]').forEach(b=>b.onclick=()=>{s.scale=b.dataset.scale;build();log('Frame '+s.scale.toUpperCase())});
$('back').onclick=()=>{s.offset=Math.max(-720,s.offset-6);build()};$('forward').onclick=()=>{s.offset=Math.min(720,s.offset+6);build()};$('now').onclick=()=>{s.offset=0;build()};$('play').onclick=()=>{s.playing=!s.playing;$('play').textContent=s.playing?'■ PAUSE':'▶ PLAY';clearInterval(s.timer);if(s.playing)s.timer=setInterval(()=>{s.offset+=6;build()},650)};
$('labels').onclick=()=>{s.labels=!s.labels;$('labels').textContent='LABELS '+(s.labels?'ON':'OFF')};$('pulse').onclick=()=>{s.pulse=1;log('Synthetic solar pulse')};$('allOn').onclick=()=>{defs.forEach(d=>s.active.add(d[0]));layers();build()};
$('reset').onclick=()=>{s.active=new Set(defs.map(d=>d[0]));s.scale='earth';s.offset=0;s.labels=s.trails=s.uncertainty=true;s.pulse=s.panX=s.panY=0;s.selected=null;clearInterval(s.timer);layers();build();log('Astronomical engine reset')};
$('center').onclick=()=>{if(!s.selected)return;const r=c.getBoundingClientRect();s.panX=r.width/2-s.selected.x;s.panY=r.height/2-s.selected.y};$('isolate').onclick=()=>{if(!s.selected)return;s.active=new Set([s.selected.layer]);layers();build()};$('trails').onclick=()=>{s.trails=!s.trails;$('trails').textContent='TRAILS '+(s.trails?'ON':'OFF')};$('uncertainty').onclick=()=>{s.uncertainty=!s.uncertainty;$('uncertainty').textContent='UNCERTAINTY '+(s.uncertainty?'ON':'OFF')};
$('selfTest').onclick=()=>log('Self-test PASS: 7 layers / canvas / time / selection');
$('export').onclick=()=>{const data={schema:'gpt-doug.astronomical-context.v1',created:new Date().toISOString(),frame:s.scale,offset_hours:s.offset,active_layers:[...s.active],objects:s.objects.map(q=>({id:q.id,layer:q.layer,context:q.ctx,confidence:q.confidence})),note:'schematic/synthetic astronomical context; not navigation or targeting'};const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=u;a.download='gpt-doug-astronomical-context.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
setInterval(ui,1000);addEventListener('resize',build);window.GPT_ASTRO={state:s,status(){return{frame:s.scale,offset_hours:s.offset,active_layers:[...s.active],objects:s.objects.length,selected:s.selected?.id||null}}};layers();build();ui();draw();