from __future__ import annotations

import json
import re
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any


class ZyraCompileError(ValueError):
    """Raised when a .zyra source file cannot be compiled deterministically."""


@dataclass(frozen=True)
class ZyraProgram:
    app_name: str
    strict: bool
    verbatim: bool
    build_text: str
    required: tuple[str, ...]
    forbidden_changes: tuple[str, ...]
    source_text: str

    def to_dict(self) -> dict[str, Any]:
        value = asdict(self)
        value["required"] = list(self.required)
        value["forbidden_changes"] = list(self.forbidden_changes)
        return value


_APP_RE = re.compile(r"\bapp\s+([A-Za-z_][A-Za-z0-9_-]*)\s*\{", re.MULTILINE)
_STRICT_RE = re.compile(r"\bstrict\s+(true|false)\b", re.IGNORECASE)
_VERBATIM_RE = re.compile(r"\bverbatim\s+(true|false)\b", re.IGNORECASE)
_BUILD_RE = re.compile(r'\bbuild\s+verbatim\s+"""(.*?)"""', re.DOTALL | re.IGNORECASE)


def _bool_from_match(match: re.Match[str] | None, default: bool) -> bool:
    if match is None:
        return default
    return match.group(1).lower() == "true"


def _extract_requirements(build_text: str) -> tuple[tuple[str, ...], tuple[str, ...]]:
    required: list[str] = []
    forbidden: list[str] = []

    for raw_line in build_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        normalized = re.sub(r"^(?:[-*+]\s+|\d+[.)]\s+)", "", line).strip()
        lower = normalized.lower()

        if lower.startswith(("do not ", "don't ", "never ", "must not ")):
            forbidden.append(normalized)
            continue

        if line.startswith(("-", "*", "+")) or re.match(r"^\d+[.)]\s+", line):
            required.append(normalized)

    return tuple(required), tuple(forbidden)


def parse_source(source: str) -> ZyraProgram:
    if not isinstance(source, str) or not source.strip():
        raise ZyraCompileError("ZYRA source is empty")

    app_match = _APP_RE.search(source)
    app_name = app_match.group(1) if app_match else "ZyraApp"

    strict = _bool_from_match(_STRICT_RE.search(source), default=True)
    verbatim = _bool_from_match(_VERBATIM_RE.search(source), default=False)

    build_match = _BUILD_RE.search(source)
    build_text = build_match.group(1).strip("\n") if build_match else ""

    if verbatim and not build_text:
        raise ZyraCompileError(
            'verbatim mode requires a build verbatim """...""" block'
        )

    required, forbidden = _extract_requirements(build_text)

    return ZyraProgram(
        app_name=app_name,
        strict=strict,
        verbatim=verbatim,
        build_text=build_text,
        required=required,
        forbidden_changes=forbidden,
        source_text=source,
    )


def _typescript_from_program(program: ZyraProgram) -> str:
    payload = json.dumps(program.to_dict(), indent=2, ensure_ascii=False)
    return (
        "// Generated by ZYRA. Do not hand-edit generated output.\n"
        "// Source intent is preserved in zyraBuildSpec.source_text.\n\n"
        f"export const zyraBuildSpec = {payload} as const;\n\n"
        "export type ZyraBuildSpec = typeof zyraBuildSpec;\n"
    )


def compile_source(source: str) -> dict[str, Any]:
    program = parse_source(source)
    manifest = program.to_dict()
    manifest["language"] = "zyra"
    manifest["compiler_version"] = 1
    manifest["verbatim_score_target"] = 100 if program.verbatim else None

    return {
        "program": program,
        "manifest": manifest,
        "typescript": _typescript_from_program(program),
    }


def compile_file(source_path: str | Path, out_dir: str | Path) -> dict[str, str]:
    source_path = Path(source_path)
    out_dir = Path(out_dir)

    if source_path.suffix != ".zyra":
        raise ZyraCompileError("source file must use the .zyra extension")

    result = compile_source(source_path.read_text(encoding="utf-8"))
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = out_dir / "zyra.manifest.json"
    typescript_path = out_dir / "zyra.generated.ts"

    manifest_path.write_text(
        json.dumps(result["manifest"], indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    typescript_path.write_text(result["typescript"], encoding="utf-8")

    return {
        "manifest": str(manifest_path),
        "typescript": str(typescript_path),
    }
