ENTITY_TYPES = (
    "Person",
    "Company",
    "CorporateNetwork",
    "Manufacturer",
    "Subsidiary",
    "Distributor",
    "Broker",
    "Intermediary",
    "Reseller",
    "Importer",
    "DefenseContractor",
    "DefenseEndUser",
    "FinancialInstitution",
    "Jurisdiction",
    "FreeZonePort",
    "Product",
    "CNCMachineTool",
    "Component",
    "Shipment",
    "ProcurementContract",
    "Sanction",
    "ExportControl",
    "EvidenceSource",
)

RELATION_TYPES = (
    "OWNS",
    "SHAREHOLDER_OF",
    "SUBSIDIARY_OF",
    "AFFILIATED_WITH",
    "MANUFACTURES",
    "ASSEMBLES",
    "RESELLS",
    "IMPORTS_FROM",
    "EXPORTS_TO",
    "SHIPS_TO",
    "DIRECTS_SHIPMENT",
    "SUPPLIES",
    "CONTRACTS_WITH",
    "LOCATED_IN",
    "SANCTIONED_BY",
    "SUBJECT_TO_EXPORT_CONTROL",
    "USES",
    "TRANSSHIPS_VIA",
    "DIVERTED_TO",
    "SOURCED_FROM_SECONDHAND_MARKET",
)

CONFIDENCE_LEVELS = (
    "confirmed",
    "reported",
    "indicated",
    "likely",
    "appears_to",
    "may_have",
    "insufficient_information",
)

EVIDENCE_TYPES = (
    "trade_data",
    "corporate_record",
    "procurement_record",
    "court_filing",
    "news",
    "social_media",
    "tax_record",
    "sanctions_record",
    "export_control_record",
    "report",
    "other",
)
