const FALLBACK={generated_at:new Date().toISOString(),quotes:[{symbol:'SPY',name:'S&P 500 ETF',price:0,change_pct:0,history:[]},{symbol:'QQQ',name:'Nasdaq 100 ETF',price:0,change_pct:0,history:[]},{symbol:'BTC-USD',name:'Bitcoin',price:0,change_pct:0,history:[]}],news:[],filings:[],sources:[{name:'Bundled fallback',status:'degraded'}]};
let data=FALLBACK;
const $=s=>document.querySelector(s), money=n=>n?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:n<10?2:0}).format(n):'N/A', pct=n=>`${n>=0?'+':''}${Number(n||0).toFixed(2)}%`, cls=n=>n>0?'up':n<0?'down':'flat', esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function quotes(){return data.quotes||[]}
function render(){
  $('#tickerTape').innerHTML=quotes().slice(0,10).map(q=>`<div class="quote"><b>${esc(q.symbol)}</b><strong>${money(q.price)}</strong><span class="${cls(q.change_pct)}">${pct(q.change_pct)}</span></div>`).join('');
  $('#marketTable').innerHTML=`<table class="data-table"><thead><tr><th>SYMBOL</th><th>NAME</th><th>PRICE</th><th>CHANGE</th><th>AS OF</th></tr></thead><tbody>${quotes().map(q=>`<tr><td><b>${esc(q.symbol)}</b></td><td>${esc(q.name)}</td><td>${money(q.price)}</td><td class="${cls(q.change_pct)}">${pct(q.change_pct)}</td><td>${esc(q.as_of||'snapshot')}</td></tr>`).join('')}</tbody></table>`;
  const avg=quotes().filter(q=>!q.symbol.includes('BTC')&&!q.symbol.includes('ETH')).reduce((a,q)=>a+Number(q.change_pct||0),0)/Math.max(1,quotes().length-2); $('#marketMood').textContent=avg>.5?'RISK-ON':avg<-.5?'RISK-OFF':'MIXED';
  const risks=deriveRisks(); $('#risks').innerHTML=risks.map(r=>`<div class="item risk"><b class="${r.score>69?'down':r.score>39?'flat':'up'}">${r.score}/100</b><div>${esc(r.name)}<div class="meter"><i style="width:${r.score}%"></i></div></div></div>`).join('');
  $('#news').innerHTML=(data.news||[]).slice(0,7).map(n=>`<div class="item"><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.title)}</a><div class="meta">${esc(n.source)} · ${esc(n.published)}</div></div>`).join('')||'<div class="item">No headlines in this snapshot.</div>';
  $('#filingList').innerHTML=(data.filings||[]).map(f=>`<div class="item"><a href="${esc(f.url)}" target="_blank" rel="noopener"><b>${esc(f.ticker||f.company)}</b> · ${esc(f.form)}</a><div>${esc(f.company)}</div><div class="meta">FILED ${esc(f.filed)}</div></div>`).join('')||'<div class="item">No filings in this snapshot.</div>';
  $('#sources').innerHTML=(data.sources||[]).map(s=>`<div class="source"><span>${esc(s.name)}</span><b>${esc(s.status||'ok').toUpperCase()}</b></div>`).join('');
  renderBrief(); renderWatch(); drawChart();
}
function deriveRisks(){const q=quotes(), spy=q.find(x=>x.symbol==='SPY')||{}, vix=q.find(x=>x.symbol==='^VIX')||{}, btc=q.find(x=>x.symbol==='BTC-USD')||{};return[{name:'Equity momentum',score:Math.round(Math.min(100,Math.max(5,50-Number(spy.change_pct||0)*12)))},{name:'Volatility regime',score:Math.round(Math.min(100,Math.max(5,Number(vix.price||18)*3.2)))},{name:'Crypto stress',score:Math.round(Math.min(100,Math.max(5,50-Number(btc.change_pct||0)*7)))},{name:'Feed freshness',score:Math.min(100,Math.round((Date.now()-new Date(data.generated_at))/36e5*8))}]}
function renderBrief(){const movers=[...quotes()].sort((a,b)=>Math.abs(b.change_pct)-Math.abs(a.change_pct)).slice(0,3), headlines=(data.news||[]).slice(0,4);$('#brief').innerHTML=`<div class="brief-block"><h3>EXECUTIVE READ</h3><p>${$('#marketMood').textContent}. Largest tracked moves: ${movers.map(x=>`${x.symbol} ${pct(x.change_pct)}`).join(', ')||'unavailable'}.</p></div><div class="brief-block"><h3>CATALYSTS</h3>${headlines.map(n=>`<p>• ${esc(n.title)}</p>`).join('')||'<p>No current headlines.</p>'}</div><div class="brief-block"><h3>RISK DISCIPLINE</h3><p>Confirm timestamps and primary sources before acting. Snapshot data is delayed, incomplete, and designed for research—not execution.</p></div>`}
function drawChart(){const c=$('#chart'),ctx=c.getContext('2d'),q=quotes().find(x=>x.symbol==='SPY')||quotes()[0],values=q?.history||[];ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#17343a';ctx.lineWidth=1;for(let i=0;i<6;i++){let y=20+i*48;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(c.width,y);ctx.stroke()}if(values.length<2){ctx.fillStyle='#7d9698';ctx.fillText('Historical series unavailable in fallback mode',24,50);return}let min=Math.min(...values),max=Math.max(...values),span=max-min||1;ctx.strokeStyle='#62ff9b';ctx.lineWidth=3;ctx.beginPath();values.forEach((v,i)=>{let x=i/(values.length-1)*(c.width-30)+15,y=c.height-20-(v-min)/span*(c.height-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#38d9ff';ctx.fillText(`${q.symbol} · ${money(q.price)} · ${values.length} sessions`,18,20)}
function getWatch(){try{return JSON.parse(localStorage.dougWatch||'["SPY","QQQ","BTC-USD"]')}catch{return[]}}function renderWatch(){const w=getWatch();$('#watchlist').innerHTML=w.map(s=>{let q=quotes().find(x=>x.symbol===s);return `<span class="pill">${esc(s)} ${q?`<i class="${cls(q.change_pct)}">${pct(q.change_pct)}</i>`:''}<button data-remove="${esc(s)}">×</button></span>`}).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{localStorage.dougWatch=JSON.stringify(getWatch().filter(x=>x!==b.dataset.remove));renderWatch()})}
function command(raw){let x=raw.trim().toUpperCase(),out='Command not recognized. Open HELP for examples.';if(/BRIEF|SUMMARY|OVERVIEW/.test(x)){out=`${$('#marketMood').textContent}: ${quotes().slice(0,5).map(q=>`${q.symbol} ${pct(q.change_pct)}`).join(' · ')}. ${data.news?.[0]?.title||'No headline available.'}`}else if(/RISK/.test(x)){out=deriveRisks().map(r=>`${r.name} ${r.score}/100`).join(' · ')}else if(/CRYPTO|BITCOIN|ETH/.test(x)){out=quotes().filter(q=>/BTC|ETH/.test(q.symbol)).map(q=>`${q.symbol} ${money(q.price)} (${pct(q.change_pct)})`).join(' · ')||'Crypto feed unavailable.'}else if(/FIL/.test(x)){out=`${data.filings?.length||0} recent filings loaded. Open SEC FILINGS for primary-source links.`}else if(/NEWS|CATALYST/.test(x)){out=(data.news||[]).slice(0,3).map(n=>n.title).join(' · ')||'News feed unavailable.'}else{let symbol=x.replace(/QUOTE|PRICE|SHOW|\?/g,'').trim().split(/\s+/)[0],q=quotes().find(v=>v.symbol===symbol);if(q)out=`${q.symbol} ${money(q.price)}, ${pct(q.change_pct)}. Snapshot: ${q.as_of||data.generated_at}.`}$('#answer').textContent=out}
async function init(){try{const r=await fetch(`data/market-snapshot.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);data=await r.json();$('#feedStatus').textContent='SNAPSHOT ONLINE'}catch{$('#feedStatus').textContent='FALLBACK MODE'}render()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active')});$('#run').onclick=()=>command($('#command').value);$('#command').onkeydown=e=>{if(e.key==='Enter')command(e.target.value)};$('#addWatch').onclick=()=>{let s=$('#watchSymbol').value.trim().toUpperCase();if(!/^[A-Z^.-]{1,12}$/.test(s))return;localStorage.dougWatch=JSON.stringify([...new Set([...getWatch(),s])]);$('#watchSymbol').value='';renderWatch()};setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString(),1000);init();
