#!/usr/bin/env python3
"""
Copyright (c) 2026 Douglas Brown Jr / Xuniaverse. Licensed under the
xuniaverse-production LICENSE (All Rights Reserved).

Trust dossier — generates a dated report of the system's actual,
verifiable security/reliability posture, built per Doug's own
recommendation (dispatched live, 2026-08-15): pull from what already
exists (Zyra's audit log, CI test results, ontology data) rather than
build new infrastructure or new claims.

Explicitly self-audited, not third-party verified. Lists known gaps
alongside real results — never rounds up.
"""
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ontology
import zyra_guard

ROOT = Path(__file__).resolve().parent.parent
WORKERS_DIR = Path(__file__).resolve().parent
OUT_PATH = ROOT / "xuni-workers" / "live" / "trust-dossier.md"

KNOWN_GAPS = [
    "No third-party security audit or penetration test has been performed.",
    "No load/stress testing at scale — throughput has only been verified with small (4-task) concurrent bursts.",
    "No formal compliance certification exists (no SOC2, no FedRAMP, no CJIS, no NIST 800-53 assessment).",
    "Zyra is a keyword/pattern/decode guard, not a semantic understanding system — it does not catch every possible evasion, only the categories it has been explicitly tested against.",
    "The system runs on a single local machine (no redundancy, no failover, no monitoring/alerting beyond local logs).",
    "Test coverage exists for zyra_guard.py and ontology.py; agent-daemon.py's retry/concurrency logic has been manually verified live but has no automated regression tests yet.",
]


def _run_test_file(filename: str) -> dict:
    path = WORKERS_DIR / filename
    if not path.exists():
        return {"file": filename, "ran": False, "reason": "file not found"}
    proc = subprocess.run([sys.executable, str(path)], capture_output=True, text=True, timeout=120)
    last_line = next((l for l in reversed(proc.stdout.strip().splitlines()) if "/" in l and "passed" in l), "")
    return {
        "file": filename,
        "ran": True,
        "returncode": proc.returncode,
        "summary": last_line or "(no summary line found)",
        "stdout": proc.stdout,
    }


def generate() -> str:
    generated_at = time.strftime("%Y-%m-%d %H:%M:%S %Z")

    test_results = [_run_test_file("test_zyra_guard.py"), _run_test_file("test_ontology.py")]

    log_integrity = zyra_guard.verify_log_integrity()
    ontology_summary = ontology.summary()

    lines = []
    lines.append("# Xuniaverse trust dossier")
    lines.append("")
    lines.append(f"Generated: {generated_at}")
    lines.append("")
    lines.append("**Status: self-audited, not third-party verified.** Everything below is computed directly from this system's own logs and test suites at generation time — no claims beyond what was actually measured.")
    lines.append("")

    lines.append("## Automated test results")
    lines.append("")
    for r in test_results:
        if not r["ran"]:
            lines.append(f"- `{r['file']}`: NOT RUN — {r['reason']}")
            continue
        status = "PASS" if r["returncode"] == 0 else "FAIL"
        lines.append(f"- `{r['file']}`: **{status}** — {r['summary']}")
    lines.append("")

    lines.append("## Audit log integrity (Zyra)")
    lines.append("")
    lines.append(f"- Valid: **{log_integrity['valid']}**")
    lines.append(f"- Entries checked: {log_integrity['entries_checked']}")
    lines.append(f"- Detail: {log_integrity['reason']}")
    lines.append("")
    lines.append("(Note: entries logged before the hash-chain feature was added, 2026-08-14, predate the chain format and are correctly reported as unverifiable rather than retroactively marked valid.)")
    lines.append("")

    lines.append("## Ontology snapshot")
    lines.append("")
    for k, v in ontology_summary["object_counts"].items():
        lines.append(f"- {k}: {v}")
    lines.append(f"- Real computed links: {ontology_summary['link_count']}")
    lines.append("")

    lines.append("## Known gaps — not hidden, listed explicitly")
    lines.append("")
    for gap in KNOWN_GAPS:
        lines.append(f"- {gap}")
    lines.append("")

    lines.append("## Provenance")
    lines.append("")
    lines.append("This dossier's contents were generated by running the actual test files and querying the actual audit log/ontology state on this machine at the timestamp above — not written from memory or aggregated from prior claims. Re-run `python3 xuni-workers/trust_dossier.py` at any time to regenerate against current state.")
    lines.append("")

    return "\n".join(lines)


def main():
    report = generate()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(report)
    print(report)
    print(f"\n--- written to {OUT_PATH} ---")


if __name__ == "__main__":
    main()
